# Generated by Django 2.0.6 on 2018-09-23 13:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 9, 23, 13, 18, 49, 910854, tzinfo=utc)),
        ),
    ]
