# Generated by Django 2.0.6 on 2018-09-23 13:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180923_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 9, 23, 13, 21, 51, 910022, tzinfo=utc)),
        ),
    ]
